repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: ^Predavanja/.*\.tex$
      - id: end-of-file-fixer
        files: ^Predavanja/.*\.tex$
      - id: mixed-line-ending
        args: [--fix=lf]
        files: ^Predavanja/.*\.tex$
